// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAArHqQtHyLfCe8wTf1tSQW-Dychz0pZw',
    appId: '1:382290728994:web:d9d38eeca97a7dce48927b',
    messagingSenderId: '382290728994',
    projectId: 'breath-noise',
    authDomain: 'breath-noise.firebaseapp.com',
    storageBucket: 'breath-noise.firebasestorage.app',
    measurementId: 'G-NJZJWQ5HJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvmOUzpyg7AZ3zTxTKpAsIYhpryjZiP4',
    appId: '1:382290728994:android:db5601160f8681c548927b',
    messagingSenderId: '382290728994',
    projectId: 'breath-noise',
    storageBucket: 'breath-noise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVtpmzT9j4_38NXBbr9v6KLbuCK-i_hzc',
    appId: '1:382290728994:ios:f1bf28a072d0c29148927b',
    messagingSenderId: '382290728994',
    projectId: 'breath-noise',
    storageBucket: 'breath-noise.firebasestorage.app',
    iosBundleId: 'com.example.luminaHearth',
  );
}
